config/config/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('main_page/', include('main_page.urls')),
    path('admin/', admin.site.urls),
]

config/main_page/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from .views import index, by_rubric, ApartmentInfoCreateView


app_name = 'main_page'

urlpatterns = [

    path('', index, name='index'),
    path('add/', ApartmentInfoCreateView.as_view(), name='add'),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/main_page/models.py
from django.db import models


class Rubric(models.Model):
    name = models.CharField(max_length=50, db_index=True, verbose_name='Категория')

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
        ordering = ['name']

    def __str__(self):
        return self.name


class ApartmentInfo(models.Model):
    title = models.CharField(max_length=500, verbose_name='Название')                                     # Заголовок объявления
    content = models.TextField(max_length=500, null=True, blank=True)                                     # Описание квартиры
    photo = models.ImageField(upload_to='uploads/%Y/%m/%d/', null=True)
    address = models.CharField(max_length=100, null=True, blank=True, verbose_name='Адрес')               # Адрес сдаваемой квартиры
    apartment_area = models.FloatField(max_length=30, verbose_name='Площадь')                             # Площадь Квартиры
    price = models.FloatField(max_length=30, null=True, blank=True)                                       # Цена в месяц
    contact = models.IntegerField(verbose_name='Контакты')                                                # Номер для связи с арендадателем
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата Публикации')    # Дата публикации
    rubric = models.ForeignKey(Rubric, null=True, on_delete=models.PROTECT, verbose_name = 'Категория')

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']

config/main_page/forms.py
from django.forms import ModelForm

from .models import ApartmentInfo


class ApartmentInfoForm(ModelForm):

    class Meta:
        model = ApartmentInfo
        fields = ('title', 'content', 'photo', 'address', 'apartment_area', 'price', 'contact', 'rubric')

config/main_page/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .models import ApartmentInfo, Rubric
from .forms import ApartmentInfoForm


def index(request):
    aparts = ApartmentInfo.objects.all()
    rubrics = Rubric.objects.all()
    context = {'aparts': aparts,
               'rubrics': rubrics, }
    return render(request, 'main_page/index.html', context)


def by_rubric(request, rubric_id):
    aparts = ApartmentInfo.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    curent_rubric = Rubric.objects.get(pk=rubric_id)

    context = {
        'aparts': aparts,
        'rubrics': rubrics,
        'curent_rubric': curent_rubric,
    }

    return render(request, 'main_page/by_rubric.html', context)


class ApartmentInfoCreateView(CreateView):
    template_name = 'main_page/create.html'
    form_class = ApartmentInfoForm
    success_url = reverse_lazy('main_page:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context

config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image ">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>

<body>
{% include 'includes/header.html' %}
<div class="container py-5">
  <main>

    {% block content %}
    {% endblock %}

  </main>

</body>
{% include 'includes/footer.html' %}
</html>

config/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
  <p>
    © 2020 Copyright <span style="color:blue">NAME
  </p>
</footer>

config/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href=" {% url 'main_page:index' %} ">
        <img src="{% static 'img/logo.png' %}" width="40" height="40" class="d-inline-block align-top" alt="">
        <span style="color:black">NAME
      </a>

      <div class="col-4" >
      {% for rubric in rubrics %}
        <a href="{% url 'main_page:by_rubric' rubric.pk %}" type="button" class="btn btn-primary  ">{{ rubric.name }}</a>
      {% endfor %}
      </div>

      <a href="{% url 'main_page:add' %}" type="button" class="btn btn-primary">Добавить объявление</a>



    </div>
  </nav>
</header>

config/templates/main_page/by_rubric.html
{% extends 'base.html' %}

{% block title %}
  Все записи группы {{ curent_rubric.name }}
{% endblock %}


{% block content %}

<h1>Все объвления: {{ curent_rubric.name }}</h1>

{% for apart in aparts %}
{% include 'main_page/includes/post_detail.html' %}


<!--{% if not forloop.last %}
<hr>
{% endif %}
!-->

{% endfor %}
{% endblock %}




























<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ curent_rubric.name }}</title>
</head>
<body>
<h1>Объявления</h1>
<h2>Категория: {{ curent_rubric.name }}</h2>


<div>
  <a href="/main_page/">Главная</a>
  {% for rubric in rubrics %}
  <a href="/main_page/{{ rubric.pk }}/">{{ rubric.name }}</a>
  {% endfor %}
</div>


{% for apart in aparts %}
<div>
  <h2>{{ apart.title }}</h2>
  <p>{{ apart.content }}</p>
  <p>{{ apart.address }}</p>
  <p>Площадь: {{ apart.apartment_area }} Кв.М.</p>
  <p>Цена: {{ apart.price }} RUB </p>
  <p>Опубликовано: {{ apart.published|date:"d.m.Y H:i:s" }}</p>
</div>
<hr>
{% endfor %}
</body>
</html>

config/templates/main_page/create.html
{% extends 'base.html' %}

{% block title %}

  Добавление Объявлений

{% endblock %}



{% block content %}
<body>

<div>
  <a href="{% url 'main_page:index' %}">Главная</a>
  {% for rubric in rubrics %}
  <a href="{% url 'main_page:by_rubric' rubric.pk %}">{{ rubric.neme }}</a>
  {% endfor %}
</div>

<form class="form-horizontal form_middle" enctype='multipart/form-data' method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Добавить" >
</form>

</body>
{% endblock %}
</html>

config/templates/main_page/includes/post_detail.html
{% load humanize %}
<p>
<div class="shadow" style="width: 70rem; border-radius: 12px;">
  <div class="card" style="width: 70rem; border-radius: 12px;">


    <div class="card-body">
      <div class="row">
        <div class="col-3 p-3 d-flex align-items-center">
          <img src="/main_page{{ apart.photo.url }}" width="250px" style="border-radius: 10px; float:left">
        </div>
        <div class="col-6 d-grid gap-2 mx-1">
          <h5 class="card-title">{{ apart.title }}</h5>
          <h6 class="card-title">{{ apart.address }}</h6>
          <h6 class="card-title">Площадь: {{ apart.apartment_area }} Кв.М.</h6>
          <h5 class="card-title">Цена: {{ apart.price|intcomma  }} RUB</h5>
          <p class="card-text">{{ apart.content|safe|truncatechars:200 }}</p>
          <h6 class="card-title" style="color:grey">Дата публикации: {{ apart.published|date:"d.m.Y H:i:s" }}</h6>
        </div>

        <div class="col d-grid gap-2 align-items-center mt-auto " >
          <a type="button" class="btn btn-primary col-md-6">{{ apart.contact }}</a>
          <a type="button" class="btn btn-secondary col-md-6">Написать</a>
        </div>
      </div>
    </div>


  </div>
</div>
</p>

<!--

          <a type="button" class="btn btn-primary col-md-4">{{ apart.contact }}</a>
          <a type="button" class="btn btn-secondary col-md-4">Написать</a>

!-->

config/templates/main_page/index.html
{% extends 'base.html' %}


{% block title %}

  Главная :: Доска Объявлений

{% endblock %}


{% block content %}
<h1>Объявления</h1>


<body>
<div>


</div>

{% for apart in aparts %}
{% include 'main_page/includes/post_detail.html' %}

{% if apart.by_rubric %}
<a href="{% url 'main_page:by_rubric' rubric.pk %}">все записи группы</a>
{% endif %}

<!--{% if not forloop.last %}
<hr>
{% endif %}
!-->

{% endfor %}
{% endblock %}

</body>
</html>